
import { APPLIANCE_LIBRARY, DEFAULT_PRICING, defaultPanel, chooseClosest, backupFromAppliances, usageCalculation, budgetCalculation, priceEstimate, economics, co2, normalizePricing } from './calc.js';
import { SUPABASE_URL, SUPABASE_KEY } from './config.js';

let supabase=null; if(SUPABASE_URL&&SUPABASE_KEY){ const mod = await import('https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm'); supabase = mod.createClient(SUPABASE_URL, SUPABASE_KEY); }
const state={equipment:[],assessments:[],pricing:{...DEFAULT_PRICING},editingId:null,last:null};
const $=id=>document.getElementById(id); const money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(Number(v||0)); const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const app = document.getElementById('app');
app.innerHTML = `
<div class="app"><aside class="sidebar"><div class="brand"><div class="brand-mark">☀</div><div><b>Solar Office Pro</b><small>Sales & Sizing Suite</small></div></div><nav class="nav"><button class="active" data-page="dashboard">ภาพรวม</button><button data-page="calculator">ประเมินระบบโซลาร์</button><button data-page="history">ประวัติลูกค้า</button><button data-page="equipment">อุปกรณ์</button><button data-page="pricing">ตั้งค่าราคา</button><button data-page="help">คู่มือ</button></nav><div class="side-status"><b>${supabase?'Supabase เชื่อมต่อแล้ว':'Demo Mode'}</b><br>คำนวณอัตโนมัติทุกครั้งที่กรอกข้อมูล</div></aside>
<main class="main">
<section id="dashboard" class="page active"><div class="topbar"><div><div class="eyebrow">DASHBOARD</div><h1>ภาพรวมงานโซลาร์</h1></div><span class="status-pill">พร้อมใช้งาน</span></div><div class="grid4"><div class="metric"><small>จำนวนการประเมิน</small><b id="dashAssessments">0</b></div><div class="metric"><small>อุปกรณ์ในระบบ</small><b id="dashEquipment">0</b></div><div class="metric"><small>มูลค่าโครงการรวม</small><b id="dashProjectValue">฿0</b></div><div class="metric"><small>ประหยัดต่อเดือนรวม</small><b id="dashSaving">฿0</b></div></div><div class="two-col"><div class="card"><div class="section-head"><div><div class="eyebrow">RECENT</div><h2>งานประเมินล่าสุด</h2></div></div><div id="recentList"></div></div><div class="card"><div class="section-head"><div><div class="eyebrow">START</div><h2>เริ่มงานใหม่</h2></div></div><p class="muted">ประเมินจากการใช้ไฟหรือจากงบประมาณได้ พร้อมแดชบอร์ดผลลัพธ์แบบใหม่</p><div class="actions"><button class="btn primary" id="goCalcBtn">ไปหน้าเครื่องคำนวณ</button></div></div></div></section>

<section id="calculator" class="page"><div class="topbar"><div><div class="eyebrow">SOLAR ESTIMATE</div><h1>ประเมินระบบโซลาร์</h1></div><span class="status-pill">Auto Calculate</span></div><div class="two-col"><div class="stack">
<div class="card"><div class="section-head"><div><div class="eyebrow">CUSTOMER</div><h2>ข้อมูลลูกค้า</h2></div></div><div class="form-grid"><label>ชื่อลูกค้า<input id="customerName" placeholder="เช่น คุณสมชาย / บริษัท ABC"></label><label>เบอร์โทร<input id="phone"></label><label>ชื่อสถานที่ / โครงการ<input id="siteName"></label><label>ประเภทระบบ<select id="systemType"><option>On-Grid</option><option>Hybrid</option></select></label><label>โหมดการประเมิน<select id="calcMode"><option value="usage">ประเมินจากการใช้ไฟ</option><option value="budget">ประเมินจากงบประมาณ</option></select></label><label>ประเภทผู้ใช้ไฟ<select id="tariffType"><option value="residential">บ้านอยู่อาศัย</option><option value="business">ธุรกิจทั่วไป</option><option value="industrial">โรงงาน / อุตสาหกรรม</option></select></label></div></div>
<div id="usageCard" class="card"><div class="section-head"><div><div class="eyebrow">USAGE</div><h2>ข้อมูลการใช้ไฟ</h2></div></div><div class="form-grid"><label>หน่วยไฟเฉลี่ยต่อเดือน (kWh) ถ้ามี<input id="monthlyKwh" type="number" value="1200"></label><label>ค่าไฟที่ลูกค้าจ่ายจากบิล (บาท/เดือน)<input id="monthlyBill" type="number" value="5000"></label><label>ใช้ไฟช่วงกลางวัน (%)<input id="daytimePercent" type="number" value="70"></label><div class="soft-info"><small>สถานะข้อมูล</small><b id="usageSourceBadge">—</b><span id="estimatedKwhLabel">—</span></div></div></div>
<div id="budgetCard" class="card"><div class="section-head"><div><div class="eyebrow">BUDGET</div><h2>ประเมินจากงบประมาณ</h2></div></div><div class="form-grid"><label>งบประมาณลูกค้า (บาท)<input id="budgetAmount" type="number" value="100000"></label><div class="soft-info"><small>หลักการทำงาน</small><b>ระบบจัดชุดอุปกรณ์ที่อยู่ในงบ</b><span>ดึงราคาจากฐานข้อมูลอุปกรณ์ + ตั้งค่าราคาติดตั้ง</span></div></div></div>
<div id="hybridCard" class="card"><div class="section-head"><div><div class="eyebrow">BACKUP</div><h2>โหลดสำรองสำหรับระบบ Hybrid</h2></div></div><div class="form-grid"><label>ต้องการสำรองกี่ชั่วโมง<input id="backupHours" type="number" step="0.5" value="5"></label><div class="soft-info"><small>Battery Auto</small><b>เลือกเครื่องใช้ไฟฟ้าแทนการกรอก kW</b><span>คำนวณ Surge เฉพาะอุปกรณ์ที่มีไฟกระชาก</span></div></div><div id="applianceGrid" class="appliance-grid"></div><div class="backup-summary"><div><span>โหลดต่อเนื่องรวม</span><b id="backupContinuous">—</b></div><div><span>โหลด Surge รวม</span><b id="backupSurge">—</b></div><div><span>Battery usable</span><b id="backupUsable">—</b></div></div></div>
<div class="card"><div class="section-head"><div><div class="eyebrow">NOTE</div><h2>หมายเหตุ</h2></div></div><label>รายละเอียดเพิ่มเติม<textarea id="notes"></textarea></label><div class="actions"><button class="btn secondary" id="saveBtn">บันทึกการประเมิน</button><button class="btn secondary" id="printBtn">พิมพ์ / PDF</button></div></div></div>

<div class="stack"><div class="kpi-grid"><div class="kpi-card kpi-green"><div class="kpi-head"><span>ประหยัดค่าไฟ / เดือน</span><span class="kpi-icon">💸</span></div><b id="kpiMonthlySaving">—</b><small id="kpiAnnualSaving">—</small></div><div class="kpi-card kpi-amber"><div class="kpi-head"><span>ระยะเวลาคืนทุน</span><span class="kpi-icon">⏱️</span></div><b id="kpiPayback">—</b><small>Simple Payback</small></div><div class="kpi-card kpi-blue"><div class="kpi-head"><span>IRR</span><span class="kpi-icon">📈</span></div><b id="kpiIrr">—</b><small id="kpiNpv">NPV (25ปี): —</small></div><div class="kpi-card kpi-purple"><div class="kpi-head"><span>กำไรสุทธิสะสม 25 ปี</span><span class="kpi-icon">🪙</span></div><b id="kpiProfit25">—</b><small id="kpiCo2">ลด CO2 ได้ — ตัน/ปี</small></div></div>
<div class="card"><div class="section-head"><div><div class="eyebrow">RESULT</div><h2>ผลลัพธ์การประเมิน</h2></div><span id="resultState" class="status-pill">พร้อมคำนวณ</span></div><div class="summary-top"><div class="big-kpi"><span>ขนาดระบบ</span><b id="installedKwp">—</b><small>kWp</small></div><div class="mini-stats"><div><span>แผงที่ใช้</span><b id="panelModel">—</b></div><div><span>จำนวนแผง</span><b id="panelCount">—</b></div><div><span>Inverter</span><b id="invTarget">—</b></div><div><span>Battery</span><b id="batTarget">—</b></div><div><span>ราคาติดตั้งรวม</span><b id="estimatedPrice">—</b></div><div><span>ประหยัด / เดือน</span><b id="saving">—</b></div></div></div><div class="recommend"><h3>อุปกรณ์ที่ระบบแนะนำ</h3><div id="recommendList">ยังไม่มีผลคำนวณ</div></div><div id="priceBreakdown" class="price-breakdown"></div></div>
<div class="card"><div class="section-head"><div><div class="eyebrow">GENERATION</div><h2>ประมาณการผลิตไฟฟ้า</h2></div></div><div class="gen-rows"><div class="gen-row"><span>การผลิตไฟฟ้าเฉลี่ย / วัน</span><b id="dailyGeneration">—</b></div><div class="gen-row"><span>การผลิตไฟฟ้า / เดือน</span><b id="monthlyGeneration">—</b></div><div class="gen-row"><span>การผลิตไฟฟ้า / ปี (ปีแรก)</span><b id="annualGeneration">—</b></div></div><div class="donut-block"><div id="donutChart" class="donut-chart"></div><div class="donut-legend"><div><span class="legend-box legend-yellow"></span> ใช้เพื่อประหยัดเต็ม</div><div><span class="legend-box legend-gray"></span> ไฟเหลือ / ไม่ได้ใช้</div></div></div></div>
<div class="card"><div class="section-head"><div><div class="eyebrow">PAYBACK CHART</div><h2>กราฟจุดคุ้มทุนและกำไร</h2></div></div><div id="chartMeta" class="muted">ระบบจะแสดงผลอัตโนมัติเมื่อกรอกข้อมูล</div><div id="barChartWrap" class="chart-wrap"></div><div class="summary-list"><div><span>ปีแรก</span><b id="profit1">—</b></div><div><span>จุดคุ้มทุน</span><b id="profitPayback">—</b></div><div><span>กำไรสะสมปีที่ 20</span><b id="profit20">—</b></div><div><span>กำไรสะสมปีที่ 25</span><b id="profit25">—</b></div></div></div></div></div></section>

<section id="history" class="page"><div class="topbar"><div><div class="eyebrow">HISTORY</div><h1>ประวัติการประเมินลูกค้า</h1></div><button class="btn secondary" id="refreshHistoryBtn">รีเฟรช</button></div><div class="card"><div class="table-wrap"><table class="table"><thead><tr><th>วันที่</th><th>ลูกค้า</th><th>โหมด</th><th>ระบบ</th><th>kWp</th><th>ราคาโครงการ</th><th>คุ้มทุน</th><th></th></tr></thead><tbody id="historyBody"></tbody></table></div></div></section>
<section id="equipment" class="page"><div class="topbar"><div><div class="eyebrow">EQUIPMENT ADMIN</div><h1>จัดการอุปกรณ์</h1></div><button class="btn secondary" id="refreshEquipmentBtn">รีเฟรช</button></div><div class="admin-grid"><div class="card"><div class="section-head"><div><h2 id="equipmentFormTitle">เพิ่มอุปกรณ์</h2></div></div><form id="equipmentForm" class="form-grid"><label>ประเภท<select id="eqCategory"><option value="panel">แผง Solar</option><option value="inverter">Inverter</option><option value="battery">Battery</option></select></label><label>ยี่ห้อ<input id="eqBrand" required></label><label>รุ่น<input id="eqModel" required></label><label>กำลังแผง Wp<input id="eqPanelWp" type="number"></label><label>กำลัง Inverter kW<input id="eqPowerKw" type="number" step="0.1"></label><label>Battery kWh<input id="eqCapacityKwh" type="number" step="0.1"></label><label>ระบบ<select id="eqSystemType"><option value="">ใช้ได้ทุกระบบ</option><option>On-Grid</option><option>Hybrid</option></select></label><label>ต้นทุน<input id="eqCost" type="number"></label><label>ราคาขาย<input id="eqSellPrice" type="number"></label><label>ใช้แผงรุ่นนี้เป็นค่าเริ่มต้น<select id="eqIsDefault"><option value="false">ไม่ใช่</option><option value="true">ใช่</option></select></label><div class="actions" style="grid-column:1/-1"><button class="btn primary" type="submit">บันทึก</button><button class="btn secondary" type="button" id="eqCancelBtn">ล้างฟอร์ม</button></div></form></div><div class="card"><div id="equipmentList" class="list"></div></div></div></section>
<section id="pricing" class="page"><div class="topbar"><div><div class="eyebrow">PRICING SETTINGS</div><h1>ตั้งค่าราคาติดตั้ง</h1></div><button class="btn secondary" id="loadPricingBtn">รีเฟรช</button></div><div class="card"><div class="section-head"><div><h2>เมนูหลังบ้านสำหรับค่าติดตั้ง</h2><p class="muted">ใช้สำหรับคำนวณราคาติดตั้งรวมทั้งโหมดการใช้ไฟและโหมดงบประมาณ</p></div></div><form id="pricingForm" class="form-grid"><label>ค่าแรงติดตั้ง / kWp<input id="laborPerKwp" type="number"></label><label>ค่าโครงสร้าง / ราง / kWp<input id="structurePerKwp" type="number"></label><label>ค่าสายไฟและอุปกรณ์ / kWp<input id="wiringPerKwp" type="number"></label><label>ค่าขนส่ง / เดินทาง<input id="transportFlat" type="number"></label><label>ค่าดำเนินการ<input id="adminFlat" type="number"></label><label>Margin (%)<input id="marginPercent" type="number"></label><label>VAT (%)<input id="vatPercent" type="number"></label><div class="actions" style="grid-column:1/-1"><button class="btn primary" type="submit">บันทึกการตั้งราคา</button></div></form></div></section>
<section id="help" class="page"><div class="topbar"><div><div class="eyebrow">GUIDE</div><h1>คู่มือใช้งาน</h1></div></div><div class="card"><ol><li>เพิ่มแผง, Inverter และ Battery ในหน้า <b>อุปกรณ์</b></li><li>ตั้งแผงค่าเริ่มต้น 1 รุ่น</li><li>ตั้งค่าแรงและต้นทุนงานติดตั้งในหน้า <b>ตั้งค่าราคา</b></li><li>ประเมินระบบจากการใช้ไฟหรือจากงบประมาณ</li><li>ถ้าเลือก Hybrid ระบบจะคำนวณ Battery จากเครื่องใช้ไฟฟ้าที่เลือก</li><li>ผลลัพธ์จะคำนวณอัตโนมัติทันที</li></ol><div class="notice">หมายเหตุ: ฟีเจอร์อ่านบิลจากรูปยังไม่ได้เชื่อม API OCR ในเวอร์ชันนี้ แต่โครงสร้างพร้อมต่อยอด</div></div></section><div class="footer">Solar Office Pro • GitHub Pages + Supabase</div></main></div>`;

function showPage(id){ document.querySelectorAll('.nav button,.page').forEach(x=>x.classList.remove('active')); document.querySelector(`.nav button[data-page="${id}"]`)?.classList.add('active'); $(id)?.classList.add('active'); if(id==='dashboard') renderDashboard(); }
document.querySelectorAll('.nav button').forEach(b=>b.addEventListener('click',()=>showPage(b.dataset.page))); $('goCalcBtn').onclick=()=>showPage('calculator');
function demoEquipment(){ return [ {id:'p1',category:'panel',brand:'Demo Solar',model:'580W Mono',panel_wp:580,cost:2500,sell_price:3200,active:true,is_default:true}, {id:'i1',category:'inverter',brand:'Demo Inverter',model:'6K On Grid',power_kw:6,cost:22000,sell_price:28000,active:true,system_type:'On-Grid'}, {id:'i2',category:'inverter',brand:'Demo Inverter',model:'10K Hybrid',power_kw:10,cost:35000,sell_price:45000,active:true,system_type:'Hybrid'}, {id:'b1',category:'battery',brand:'Demo Battery',model:'10kWh LFP',capacity_kwh:10,cost:65000,sell_price:82000,active:true,system_type:'Hybrid'}, {id:'b2',category:'battery',brand:'Demo Battery',model:'15kWh LFP',capacity_kwh:15,cost:82000,sell_price:99000,active:true,system_type:'Hybrid'} ]; }
async function loadEquipment(){ if(!supabase){ state.equipment = demoEquipment(); renderEquipment(); renderDashboard(); calc(); return; } const {data,error}=await supabase.from('equipment').select('*').order('category').order('brand'); state.equipment = error ? demoEquipment() : (data||[]); renderEquipment(); renderDashboard(); calc(); }
async function loadAssessments(){ if(!supabase){ state.assessments=[]; renderHistory(); renderDashboard(); return; } const {data,error}=await supabase.from('assessments').select('*').order('created_at',{ascending:false}); state.assessments = error?[]:(data||[]); renderHistory(); renderDashboard(); }
async function loadPricing(){ if(!supabase){ state.pricing={...DEFAULT_PRICING}; fillPricing(); calc(); return; } const {data,error}=await supabase.from('pricing_settings').select('*').limit(1).maybeSingle(); state.pricing = normalizePricing(error?DEFAULT_PRICING:(data||DEFAULT_PRICING)); fillPricing(); calc(); }
function fillPricing(){ $('laborPerKwp').value=state.pricing.labor_per_kwp; $('structurePerKwp').value=state.pricing.structure_per_kwp; $('wiringPerKwp').value=state.pricing.wiring_per_kwp; $('transportFlat').value=state.pricing.transport_flat; $('adminFlat').value=state.pricing.admin_flat; $('marginPercent').value=state.pricing.margin_percent; $('vatPercent').value=state.pricing.vat_percent; }
function buildAppliances(){ $('applianceGrid').innerHTML = APPLIANCE_LIBRARY.map(a=>`<div class="appliance-card"><div class="appliance-head"><b>${a.name}</b><small>${a.powerW} W ${a.hasSurge?'• Surge':''}</small></div><input class="appliance-qty" data-id="${a.id}" type="number" min="0" value="0"></div>`).join(''); }
function applianceQtys(){ const out={}; document.querySelectorAll('.appliance-qty').forEach(el=>out[el.dataset.id]=Number(el.value||0)); return out; }
function syncSections(){ $('usageCard').style.display = $('calcMode').value==='usage' ? 'block' : 'none'; $('budgetCard').style.display = $('calcMode').value==='budget' ? 'block' : 'none'; $('hybridCard').style.display = $('systemType').value==='Hybrid' ? 'block' : 'none'; }
function badge(source,kwh){ if(source==='actual'){ $('usageSourceBadge').textContent='ใช้หน่วยจริงจากบิล'; $('estimatedKwhLabel').textContent=`${kwh.toFixed(0)} kWh/เดือน`; } else if(source==='estimated'){ $('usageSourceBadge').textContent='ประมาณจากยอดบิลอัตโนมัติ'; $('estimatedKwhLabel').textContent=`${kwh.toFixed(0)} kWh/เดือน (ประมาณการ)`; } else { $('usageSourceBadge').textContent='ข้อมูลยังไม่ครบ'; $('estimatedKwhLabel').textContent='กรอกหน่วยไฟหรือยอดบิล'; } }
function renderDonut(r){ const used=Math.max(0,Math.min(1,Number(r||0))); const C=2*Math.PI*54, d=C*used; $('donutChart').innerHTML=`<svg viewBox="0 0 160 160" width="180" height="180"><circle cx="80" cy="80" r="54" fill="none" stroke="#e3e7eb" stroke-width="18"></circle><circle cx="80" cy="80" r="54" fill="none" stroke="#efb300" stroke-width="18" stroke-linecap="round" stroke-dasharray="${d} ${C}" transform="rotate(-90 80 80)"></circle><circle cx="80" cy="80" r="30" fill="#fff"></circle><text x="80" y="76" text-anchor="middle" class="donut-number">${(used*100).toFixed(0)}%</text><text x="80" y="96" text-anchor="middle" class="donut-label">ใช้เอง</text></svg>`; }
function shortMoney(v){ const a=Math.abs(v), s=v<0?'-':''; if(a>=1000000) return s+(a/1000000).toFixed(1)+'ล.'; if(a>=1000) return s+Math.round(a/1000)+'k'; return s+Math.round(a); }
function renderBar(points,payback){ const W=820,H=340,p={t:22,r:18,b:52,l:70}; const vals=points.map(x=>x.cumulative), minY=Math.min(...vals,0), maxY=Math.max(...vals,0), span=Math.max(1,maxY-minY), cw=W-p.l-p.r, ch=H-p.t-p.b, bw=Math.max(10,cw/points.length-3), x=i=>p.l+i*(cw/points.length)+1, y=v=>p.t+((maxY-v)/span)*ch, z=y(0), ticks=Array.from({length:6},(_,i)=>minY+((maxY-minY)*i/5)); const payIndex=payback==null?null:Math.round(payback); $('barChartWrap').innerHTML = `<svg viewBox="0 0 ${W} ${H}" class="svg-chart">${ticks.map(v=>`<line x1="${p.l}" y1="${y(v)}" x2="${W-p.r}" y2="${y(v)}" stroke="#edf0f3"/><text x="${p.l-8}" y="${y(v)+4}" text-anchor="end" class="tick">${shortMoney(v)}</text>`).join('')}<line x1="${p.l}" y1="${z}" x2="${W-p.r}" y2="${z}" stroke="#88929c" stroke-width="1.5"/>${points.map((pt,i)=>{ const top=Math.min(z,y(pt.cumulative)), h=Math.abs(z-y(pt.cumulative)), c=pt.cumulative>=0?'#16a34a':'#f59e0b'; const lab=i===0||i===1||i===10||i===20||i===25||i===payIndex; const yr=i===0||i===1||i%5===0||i===points.length-1; return `<rect x="${x(i)}" y="${top}" width="${bw}" height="${Math.max(1,h)}" rx="3" fill="${c}"></rect>${lab?`<text x="${x(i)+bw/2}" y="${pt.cumulative>=0?top-6:top+h+14}" text-anchor="middle" class="tick">${shortMoney(pt.cumulative)}</text>`:''}${yr?`<text x="${x(i)+bw/2}" y="${H-18}" text-anchor="middle" class="tick">ปี ${pt.year}</text>`:''}`; }).join('')}${payIndex!==null&&points[payIndex]?`<line x1="${x(payIndex)+bw/2}" y1="${p.t}" x2="${x(payIndex)+bw/2}" y2="${H-p.b}" stroke="#2563eb" stroke-dasharray="4 4"/>`:''}</svg>`; }
function empty(msg='ข้อมูลยังไม่ครบ'){ $('resultState').textContent=msg; ['installedKwp','panelModel','panelCount','invTarget','batTarget','estimatedPrice','saving','kpiMonthlySaving','kpiAnnualSaving','kpiPayback','kpiIrr','kpiProfit25','dailyGeneration','monthlyGeneration','annualGeneration','profit1','profitPayback','profit20','profit25','backupContinuous','backupSurge','backupUsable'].forEach(id=>$(id).textContent='—'); $('kpiNpv').textContent='NPV (25ปี): —'; $('kpiCo2').textContent='ลด CO2 ได้ — ตัน/ปี'; $('recommendList').innerHTML='ยังไม่มีผลคำนวณ'; $('priceBreakdown').innerHTML=''; $('chartMeta').textContent='ระบบจะแสดงผลอัตโนมัติเมื่อกรอกข้อมูล'; $('barChartWrap').innerHTML=''; renderDonut(0); }
function calc(){ syncSections(); const panel = defaultPanel(state.equipment); if(!panel){ empty('ยังไม่มีแผง Solar'); return; }
 const backup = $('systemType').value==='Hybrid' ? backupFromAppliances(applianceQtys(), $('backupHours').value) : {continuousKw:0,surgeKw:0,usableKwh:0,batteryKwh:0}; $('backupContinuous').textContent=`${backup.continuousKw.toFixed(2)} kW`; $('backupSurge').textContent=`${backup.surgeKw.toFixed(2)} kW`; $('backupUsable').textContent=`${backup.usableKwh.toFixed(1)} kWh`;
 let panelCount=0, kwp=0, inverter=null, battery=null, batteryCount=0, price=null, eco=null, genMonth=0, genYear=0, genDay=0, saveMonth=0, saveYear=0, ratio=0, usageSource='none', monthlyKwh=0;
 if($('calcMode').value==='usage'){
   const s = usageCalculation({ monthlyKwh:$('monthlyKwh').value, monthlyBill:$('monthlyBill').value, tariffType:$('tariffType').value, daytimePercent:$('daytimePercent').value, panelWp:panel.panel_wp }); badge(s.source,s.monthlyKwh); usageSource=s.source; monthlyKwh=s.monthlyKwh; panelCount=s.panelCount; kwp=s.kwp; genMonth=s.genMonth; genYear=s.genYear; genDay=s.genDay; saveMonth=s.saveMonth; saveYear=s.saveYear; ratio=s.selfUseRatio; const invTarget=Math.max(s.invTarget, $('systemType').value==='Hybrid'?backup.continuousKw*1.25:0, $('systemType').value==='Hybrid'?backup.surgeKw:0); inverter=chooseClosest(state.equipment,'power_kw',invTarget,'inverter',$('systemType').value); battery = $('systemType').value==='Hybrid' && backup.batteryKwh>0 ? chooseClosest(state.equipment,'capacity_kwh',backup.batteryKwh,'battery','Hybrid') : null; batteryCount = battery && backup.batteryKwh>0 ? Math.max(1, Math.ceil(backup.batteryKwh/Number(battery.capacity_kwh||1))) : 0; price = priceEstimate({ panel, panelCount, inverter, battery, batteryCount, pricing:state.pricing }); eco = economics(price.total, saveYear);
 } else {
   badge('none',0); const b = budgetCalculation({ budget:$('budgetAmount').value, systemType:$('systemType').value, panel, items:state.equipment, pricing:state.pricing, backup }); if(!b){ empty('งบประมาณยังไม่พอสำหรับจัดชุด'); return; } panelCount=b.panelCount; kwp=b.kwp; inverter=b.inverter; battery=b.battery; batteryCount=b.batteryCount; price=b.price; genMonth=b.genMonth; genYear=b.genYear; genDay=b.genDay; ratio=0.8; const kwh = Number($('monthlyKwh').value||0), bill = Number($('monthlyBill').value||0), effRate = kwh>0&&bill>0 ? bill/kwh : 4.2; saveMonth = genMonth * Math.min(1, Number($('daytimePercent').value||70)/100) * effRate; saveYear = saveMonth*12; eco = economics(price.total, saveYear); }
 const payback = eco.payback ? eco.payback+' ปี' : 'เกิน 25 ปี'; state.last={ panel,panelCount,kwp,inverter,battery,batteryCount,price,eco,genMonth,genYear,genDay,saveMonth,saveYear,ratio,backup,usageSource,monthlyKwh,systemType:$('systemType').value,calcMode:$('calcMode').value,co2:co2(genYear) };
 $('resultState').textContent='คำนวณอัตโนมัติแล้ว'; $('installedKwp').textContent=kwp.toFixed(2); $('panelModel').textContent=`${panel.brand} ${panel.model} (${panel.panel_wp}Wp)`; $('panelCount').textContent=panelCount; $('invTarget').textContent=inverter?`${inverter.brand} ${inverter.model}`:'—'; $('batTarget').textContent=$('systemType').value==='Hybrid' ? (backup.batteryKwh>0?`${backup.batteryKwh.toFixed(1)} kWh`:'ไม่ต้องใช้') : 'ไม่ใช้'; $('estimatedPrice').textContent=money(price.total); $('saving').textContent=money(saveMonth); $('kpiMonthlySaving').textContent=money(saveMonth); $('kpiAnnualSaving').textContent=`${money(saveYear)} / ปี (ปีแรก)`; $('kpiPayback').textContent=payback; $('kpiIrr').textContent=eco.irr==null?'—':eco.irr.toFixed(1)+'%'; $('kpiNpv').textContent=`NPV (25ปี): ${money(eco.npv)}`; $('kpiProfit25').textContent=money(eco.profit25); $('kpiCo2').textContent=`ลด CO2 ได้ ${state.last.co2.toFixed(1)} ตัน/ปี`; $('dailyGeneration').textContent=`${genDay.toFixed(1)} kWh/วัน`; $('monthlyGeneration').textContent=`${genMonth.toFixed(0)} kWh/เดือน`; $('annualGeneration').textContent=`${genYear.toFixed(0)} kWh/ปี`; $('profit1').textContent=money(eco.profit1); $('profitPayback').textContent=payback; $('profit20').textContent=money(eco.profit20); $('profit25').textContent=money(eco.profit25); $('recommendList').innerHTML=`<div>แผง: <b>${esc(panel.brand)} ${esc(panel.model)}</b> × ${panelCount}</div><div>Inverter: <b>${inverter?esc(inverter.brand+' '+inverter.model):'ยังไม่มีรุ่นในฐานข้อมูล'}</b></div><div>Battery: <b>${$('systemType').value==='Hybrid' ? (battery?esc(battery.brand+' '+battery.model+' × '+batteryCount):'ยังไม่มีรุ่นในฐานข้อมูล') : 'ไม่ใช้สำหรับ On-Grid'}</b></div>`; $('priceBreakdown').innerHTML=`<div class="price-item"><span>ราคาแผง</span><b>${money(price.panelTotal)}</b></div><div class="price-item"><span>ราคา Inverter</span><b>${money(price.inverterTotal)}</b></div><div class="price-item"><span>ราคา Battery</span><b>${money(price.batteryTotal)}</b></div><div class="price-item"><span>ค่าแรงติดตั้ง</span><b>${money(price.labor)}</b></div><div class="price-item"><span>ค่าโครงสร้าง / ราง</span><b>${money(price.structure)}</b></div><div class="price-item"><span>ค่าสายไฟและอุปกรณ์</span><b>${money(price.wiring)}</b></div><div class="price-item"><span>ค่าขนส่ง</span><b>${money(price.transport)}</b></div><div class="price-item"><span>ค่าดำเนินการ</span><b>${money(price.admin)}</b></div><div class="price-item"><span>Margin</span><b>${money(price.margin)}</b></div><div class="price-item"><span>VAT</span><b>${money(price.vat)}</b></div>`; $('chartMeta').innerHTML=`<b>จุดคุ้มทุน:</b> ${payback} • <b>กำไรสุทธิ 25 ปี:</b> ${money(eco.profit25)}`; renderDonut(ratio); renderBar(eco.points, eco.payback); }
async function saveAssessment(){ if(!supabase || !state.last){ alert('ยังไม่ได้เชื่อม Supabase หรือยังไม่มีผลคำนวณ'); return; } const r=state.last; const payload={ customer_name:$('customerName').value||'ไม่ระบุชื่อ', phone:$('phone').value, site_name:$('siteName').value, system_type:r.systemType, calc_mode:r.calcMode, monthly_kwh:r.monthlyKwh||0, daytime_percent:Number($('daytimePercent').value||0), panel_wp:Number(r.panel.panel_wp||0), recommended_kwp:r.kwp, panel_count:r.panelCount, inverter_kw:Number(r.inverter?.power_kw||0), battery_kwh:Number(r.backup?.batteryKwh||0), project_price:r.price.total, monthly_saving:r.saveMonth, payback_year:r.eco.payback, final_profit:r.eco.profit25, selected_panel:`${r.panel.brand} ${r.panel.model}`, selected_inverter:r.inverter?`${r.inverter.brand} ${r.inverter.model}`:null, selected_battery:r.battery?`${r.battery.brand} ${r.battery.model}`:null, notes:$('notes').value }; const {error}=await supabase.from('assessments').insert(payload); if(error) alert('บันทึกไม่สำเร็จ: '+error.message); else { alert('บันทึกการประเมินแล้ว'); loadAssessments(); } }
function renderHistory(){ const body=$('historyBody'); if(!state.assessments.length){ body.innerHTML='<tr><td colspan="8"><div class="empty">ยังไม่มีประวัติการประเมิน</div></td></tr>'; return; } body.innerHTML=state.assessments.map(a=>`<tr><td>${new Date(a.created_at).toLocaleDateString('th-TH')}</td><td>${esc(a.customer_name)}</td><td>${esc(a.calc_mode||'-')}</td><td><span class="tag">${esc(a.system_type||'-')}</span></td><td>${Number(a.recommended_kwp||0).toFixed(2)}</td><td>${money(a.project_price)}</td><td>${a.payback_year?a.payback_year+' ปี':'-'}</td><td><button class="btn danger small" onclick="window.delAsmt('${a.id}')">ลบ</button></td></tr>`).join(''); }
window.delAsmt = async id => { if(!supabase || !confirm('ยืนยันลบรายการนี้?')) return; const {error}=await supabase.from('assessments').delete().eq('id',id); if(error) alert(error.message); else loadAssessments(); };
function renderDashboard(){ $('dashAssessments').textContent=state.assessments.length; $('dashEquipment').textContent=state.equipment.length; $('dashProjectValue').textContent=money(state.assessments.reduce((s,a)=>s+Number(a.project_price||0),0)); $('dashSaving').textContent=money(state.assessments.reduce((s,a)=>s+Number(a.monthly_saving||0),0)); $('recentList').innerHTML = state.assessments.length ? state.assessments.slice(0,5).map(a=>`<div class="item"><div><b>${esc(a.customer_name)}</b><span>${Number(a.recommended_kwp||0).toFixed(2)} kWp • ${money(a.project_price)}</span></div><span class="tag">${a.payback_year?a.payback_year+' ปี':'-'}</span></div>`).join('') : '<div class="empty">ยังไม่มีงานประเมิน</div>'; }
function renderEquipment(){ $('equipmentList').innerHTML = state.equipment.length ? state.equipment.map(x=>`<div class="item"><div><small>${x.category}${x.category==='panel'&&x.is_default?' • ค่าเริ่มต้น':''}</small><b>${esc(x.brand)} ${esc(x.model)}</b><span>${x.panel_wp?x.panel_wp+' Wp':x.power_kw?x.power_kw+' kW':x.capacity_kwh?x.capacity_kwh+' kWh':'-'} • ${money(x.sell_price)}</span></div><div class="item-actions">${supabase?`<button class="btn secondary small" onclick="window.editEq('${x.id}')">แก้ไข</button><button class="btn danger small" onclick="window.delEq('${x.id}')">ลบ</button>`:''}</div></div>`).join('') : '<div class="empty">ยังไม่มีอุปกรณ์</div>'; }
$('equipmentForm').addEventListener('submit', async e=>{ e.preventDefault(); if(!supabase){ alert('ยังไม่ได้เชื่อม Supabase'); return; } const payload={ category:$('eqCategory').value, brand:$('eqBrand').value, model:$('eqModel').value, panel_wp:$('eqPanelWp').value?Number($('eqPanelWp').value):null, power_kw:$('eqPowerKw').value?Number($('eqPowerKw').value):null, capacity_kwh:$('eqCapacityKwh').value?Number($('eqCapacityKwh').value):null, system_type:$('eqSystemType').value||null, cost:Number($('eqCost').value||0), sell_price:Number($('eqSellPrice').value||0), active:true, is_default:$('eqIsDefault').value==='true' }; if(payload.category==='panel' && payload.is_default){ await supabase.from('equipment').update({is_default:false}).eq('category','panel'); } const res = state.editingId ? await supabase.from('equipment').update(payload).eq('id',state.editingId) : await supabase.from('equipment').insert(payload); if(res.error) alert(res.error.message); else { resetEq(); loadEquipment(); } });
window.editEq = id => { const x=state.equipment.find(i=>i.id===id); if(!x) return; state.editingId=id; $('equipmentFormTitle').textContent='แก้ไขอุปกรณ์'; $('eqCategory').value=x.category; $('eqBrand').value=x.brand; $('eqModel').value=x.model; $('eqPanelWp').value=x.panel_wp||''; $('eqPowerKw').value=x.power_kw||''; $('eqCapacityKwh').value=x.capacity_kwh||''; $('eqSystemType').value=x.system_type||''; $('eqCost').value=x.cost||0; $('eqSellPrice').value=x.sell_price||0; $('eqIsDefault').value=x.is_default?'true':'false'; };
window.delEq = async id => { if(!supabase||!confirm('ยืนยันลบอุปกรณ์?')) return; const {error}=await supabase.from('equipment').delete().eq('id',id); if(error) alert(error.message); else loadEquipment(); };
function resetEq(){ state.editingId=null; $('equipmentFormTitle').textContent='เพิ่มอุปกรณ์'; $('equipmentForm').reset(); $('eqIsDefault').value='false'; }
$('pricingForm').addEventListener('submit', async e=>{ e.preventDefault(); const payload={ id:1, labor_per_kwp:Number($('laborPerKwp').value||0), structure_per_kwp:Number($('structurePerKwp').value||0), wiring_per_kwp:Number($('wiringPerKwp').value||0), transport_flat:Number($('transportFlat').value||0), admin_flat:Number($('adminFlat').value||0), margin_percent:Number($('marginPercent').value||0), vat_percent:Number($('vatPercent').value||0) }; state.pricing=normalizePricing(payload); if(!supabase){ alert('บันทึกใน Demo Mode แล้ว'); calc(); return; } const {error}=await supabase.from('pricing_settings').upsert(payload); if(error) alert(error.message); else { alert('บันทึกการตั้งราคาแล้ว'); loadPricing(); } });
['systemType','calcMode','tariffType','monthlyKwh','monthlyBill','daytimePercent','budgetAmount','backupHours','notes'].forEach(id=>{ $(id).addEventListener('input',()=>calc()); $(id).addEventListener('change',()=>calc()); }); document.addEventListener('input',e=>{ if(e.target.classList.contains('appliance-qty')) calc(); }); $('saveBtn').onclick=saveAssessment; $('printBtn').onclick=()=>window.print(); $('refreshHistoryBtn').onclick=loadAssessments; $('refreshEquipmentBtn').onclick=loadEquipment; $('loadPricingBtn').onclick=loadPricing; $('eqCancelBtn').onclick=resetEq; buildAppliances(); await loadEquipment(); await loadAssessments(); await loadPricing(); calc();
